Update .circleci/config.yml bundle size config, correct env

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -28,8 +28,8 @@ jobs:
             export BUNDLE_SIZE_MESSAGE="$(npx @financial-times/origami-bundle-size-cli)"
             echo "${BUNDLE_SIZE_MESSAGE}"
             export COMMENT_DATA="{\"body\":\"$(printenv BUNDLE_SIZE_MESSAGE | sed ':a;N;$!ba;s/\n/\\n/g')\"}"
-            [[ "${PULL_REQUEST}" ]] && echo "Posting bundle size to PR https://github.com/Financial-Times/${CIRCLE_PR_REPONAME}/pull/${PULL_REQUEST}" || echo "Could not find pull request to post bundle sizes to."
-            [[ "${PULL_REQUEST}" ]] && curl -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/repos/Financial-Times/${CIRCLE_PR_REPONAME}/issues/${PULL_REQUEST}/comments --data "${COMMENT_DATA}" --header "Content-Type:application/json" &> /dev/null
+            [[ "${PULL_REQUEST}" ]] && echo "Posting bundle size to PR https://github.com/Financial-Times/${CIRCLE_PROJECT_REPONAME}/pull/${PULL_REQUEST}" || echo "Could not find pull request to post bundle sizes to."
+            [[ "${PULL_REQUEST}" ]] && curl -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/repos/Financial-Times/${CIRCLE_PROJECT_REPONAME}/issues/${PULL_REQUEST}/comments --data "${COMMENT_DATA}" --header "Content-Type:application/json" &> /dev/null
   publish_to_npm:
     docker:
       - image: circleci/node:10
